const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    version: '1.0.0',
    title: 'ExpressJS REST API',
    description:
      '<h4>Documentation automatically generated by <b>swagger-autogen</b></h4>',
  },
  host: 'localhost:5000',
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Home',
      description: 'Home page of application',
    },
    {
      name: 'Users',
      description: 'Users API',
    },
    {
      name: 'Permissions',
      description: 'Permissions API',
    },
    {
      name: 'Roles',
      description: 'Roles API',
    },
    {
      name: 'Login',
      description: 'Login Page',
    },
  ],
  definitions: {
    User: {
      username: 'default_username',
      password: 'password',
      active: true,
    },
    Permission: {
      name: 'default_name',
      description: 'Permission test description...',
      active: true,
    },
    Role: {
      name: 'default_name',
      description: 'Role test description...',
      active: true,
    },
    Login: {
      username: 'user1',
      password: 'pass',
    },
  },
};

const outputFile = './docs/swagger.json';
const endpointsFiles = ['./index.js'];

swaggerAutogen(outputFile, endpointsFiles, doc);
